# Generated by Django 5.2 on 2025-04-04 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auto',
            old_name='marca',
            new_name='marcas',
        ),
    ]
