# Generated by Django 5.2 on 2025-04-04 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0002_rename_marca_auto_marcas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auto',
            old_name='marcas',
            new_name='marca',
        ),
        migrations.RemoveField(
            model_name='auto',
            name='año',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='autos_interesados',
        ),
        migrations.AddField(
            model_name='auto',
            name='anio',
            field=models.PositiveIntegerField(default=2020),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='apellido',
            field=models.CharField(default=2020, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(default=2020, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
